# Generated by Django 3.2 on 2021-04-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Showcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=254)),
                ('start_date', models.CharField(blank=True, default='', max_length=254)),
                ('start_time', models.CharField(blank=True, default='', max_length=254)),
                ('location', models.CharField(blank=True, default='', max_length=254)),
                ('entry_fee', models.CharField(blank=True, default='', max_length=254)),
            ],
        ),
    ]
