# Generated by Django 3.2 on 2021-07-01 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_alter_review_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='date_posted',
        ),
    ]
