# Generated by Django 3.2 on 2021-04-30 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210430_0825'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
